### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by GFNiko** [pbaity/rocketchat-dark-mode#211]
**Describe the bug**
I hosted rocket.chat in my own docker environment and I copy pasted your code in the respective fields in the layout (custom csss and  Custom Script for Logged In Users)
Reloaded the page afterwards with ctrl+shift+r, logged out and back in, but nothing changed. Installed the desktop app and it looks the same as the website. And there is also no extra button in the upper area beside the username.

**Expected behavior**
Dark mode in all important areas

**Screenshots**
![image](https://user-images.githubusercontent.com/114079308/216046165-65a6835c-788d-44ef-820f-7ff7af4333a9.png)
![image](https://user-images.githubusercontent.com/114079308/216046356-52cf53db-8150-4681-9759-78e360dd20aa.png)
![image](https://user-images.githubusercontent.com/114079308/216052366-8bd8224d-8805-47e0-b1cf-b3905fe00753.png)

**Desktop (please complete the following information):**
 - Windows 10 
 - LibreWolf 108
 - Version 5.4.0

**Comment by pbaity** [comment]
@GFNiko the dark mode toggle button is added to the menu at the top of the side nav on the left. Can you check there? (It's the sun icon)

![image](https://user-images.githubusercontent.com/39106297/216128474-4d09b1f7-6aec-4f51-9073-02c3ec137b69.png)

**Comment by GFNiko** [comment]
No it's not there
![image](https://user-images.githubusercontent.com/114079308/216259297-8ec84881-c814-4ce4-8316-a656fff6ebca.png)

**Comment by pbaity** [comment]
@GFNiko What version of Rocket.Chat are you running? If you can give me the steps you followed to set it up I'll try to recreate.

It may be an issue in a new version of Rocket.Chat. I suspect maybe the class names we use to select the side nav for adding the toggle button have changed.

**Comment by GFNiko** [comment]
It's version 5.4.0. I guess it is this because I cannot see a 5.4 version from the dark mode.
My steps as I wrote in the OP are as follows:

> I copy pasted your code in the respective fields in the layout (custom csss and Custom Script for Logged In Users). Reloaded the page afterwards with ctrl+shift+r, logged out and back in, but nothing changed. Installed the desktop app and it looks the same as the website. And there is also no extra button in the upper area beside the username.

If you want to know more, I am afraid, you have to ask for explicit details since I am not familiar with this. But I understand HTML and CSS (Javascript not so much unfortunately) if this would be needed

**Comment by pbaity** [comment]
Sorry, I meant to ask for the steps you followed to deploy your Rocket.Chat instance with Docker. I don't need too much detail because the deployment method shouldn't effect whether dark mode works. The Rocket.Chat version is what matters.

Just to confirm though, did you follow [Rocket.Chat's docs for deploying with docker-compose](https://docs.rocket.chat/deploy/prepare-for-your-deployment/rapid-deployment-methods/docker-and-docker-compose)?

**Comment by GFNiko** [comment]
Mostly, minor changes. Here is my docker-compose file:

```
version: '3.4'

services:
  rocketchat:
    image: rocket.chat:5
    restart: on-failure
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3030
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://rocketchat-db:27017/local?replicaSet=rs0&directConnection=true
      - DEPLOY_METHOD=docker
    depends_on:
      - mongo
    networks:
      - internal
    ports:
      - 3030:3030

  mongo:
    image: mongo:4.4
    container_name: rocketchat-db
    restart: on-failure
    volumes:
     - ./data/db:/data/db
     - ./data/dump:/dump
    command: mongod --dbpath /data/db --oplogSize 128 --replSet rs0 --storageEngine wiredTiger
    networks:
      - internal

  mongo-init-replica:
    image: mongo:4.4
    command: 'bash -c "for i in `seq 1 30`; do mongo rocketchat-db/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i t imes. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - mongo
    networks:
      - internal

networks:
    internal:
        name: internal
        external: false
```
