### ISSUE TITLE
input contrast problems

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#23]
**Describe the bug**
I see some contrast issues after we updated our server to version 3.0.2

**To Reproduce**
1. Open channels **Member List**
2. Click **Add users** button
3. Start input in **Invite Users** field
4. See contrast error on input test

**Expected behavior**
Text must be white

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/75753045-f2ba3f80-5d3a-11ea-9b27-21b28953db0c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 80
 - Version 2.17.7

**Additional context**
RC server version 3.0.2

**Comment by ankar84** [comment]
```
body.dark-mode .rc-tags__input {
	color: var(--color-white);
}
```
fixed that issue
![image](https://user-images.githubusercontent.com/4023037/75753183-44fb6080-5d3b-11ea-923d-675918e7f3af.png)

**Comment by ankar84** [comment]
It was fixed by #11, but bug still in code. I don't know why.

**Comment by pbaity** [comment]
I just noticed there's this rule in the default style:
```css
input, select, textarea {
    color: #444;
    background-color: transparent;
    border-color: #e6e6e6;
    border-style: solid;
}
```
That `color` is the issue. In our stylesheet we've got this rule to overwrite the dark color:
```css
select {
	color: var(--input-text-color);
}
```
So I think we just need to update to:
```css
input, select, textarea {
	color: var(--input-text-color);
}
```
