### ISSUE TITLE
Change mouse over background or text color from white.

### ISSUE THREAD

**Issue by nrenich** [pbaity/rocketchat-dark-mode#41]
This is just an observation and maybe there is an easy fix for this display change request. With Rocket Chat version 3.4.1 I have noticed that when you enable dark mode, any posts in a channel when you mouse over switches to a white background with white text making it unreadable.  Links are ok as they are blue.

Options to fix would be to either have a dark grey highlight on mouse over, or switch the text to black on mouse over. I'd prefer the dark grey background as white is just so jarring when using dark mode.

If anyone knows the location in the CSS to change the mouse over highlight background I will test and report back.
Thank you.

**Comment by VVvKamper** [comment]
you could add something like 
```css
body.dark-mode .message.active,.message:hover {
    background-color: #343840
}
```
to fix this. but maybe there is better option

**Comment by VVvKamper** [comment]
better like this
```css
body.dark-mode .message.active,body.dark-mode .message:hover {
    background-color: var(--color-dark-medium)
}
```
