### ISSUE TITLE
Hover theme

### ISSUE THREAD

**Issue by adipose** [pbaity/rocketchat-dark-mode#52]
Can the hover menu on the messages be themed?

![image](https://user-images.githubusercontent.com/3324395/90179162-e44c6700-dd61-11ea-8a96-2a6df8fdfe15.png)

3.5.1 has this, not sure when it first showed up.

**Comment by pbaity** [comment]
I noticed this suddenly popped up today when our snap updated to 3.5.1. Try these colors and let me know what you think:

```css
body.dark-mode .message-actions, 
body.dark-mode .rc-member-list__counter {
    color: var(--color-gray-lightest);
    background-color: var(--color-dark-80);
    border-color: var(--color-dark-70);
}

body.dark-mode .message-actions__button:hover, 
body.dark-mode .message-actions__menu:hover {
    background-color: var(--color-dark-light);
}
```

That first rule already exists so you will either need to throw that one in at the end to overrule or replace the rule. If people like these colors I'll open a PR for it.
