### ISSUE TITLE
Unread message indicator of Threads is invisible 

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#69]
**Describe the bug**
Unread message indicator of Threads is invisible in Dark mode

**To Reproduce**
1. Make a Thread
2. Get unread message in thread
3. There is no blue dot (unread message indicator) in dark mode
4. In normal mode all fine

**Expected behavior**
Blue dot should be visible

**Screenshots**
Normal mode
![image](https://user-images.githubusercontent.com/4023037/94644024-d1312e80-02f0-11eb-817e-b6b234f5abdc.png)

Dark mode
![image](https://user-images.githubusercontent.com/4023037/94644044-df7f4a80-02f0-11eb-8ff7-d82e9854c2d1.png)

In main windows all fine - blue dot visible
![image](https://user-images.githubusercontent.com/4023037/94644233-67655480-02f1-11eb-910e-e6a242944deb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Desktop RC version
 - Version 2.17.7

**Additional context**
Server 3.6.3

**Comment by pbaity** [comment]
I thought I had solved this issue by adding this rule:
```css
body.dark-mode div.rcx-box.rcx-box--full[aria-label="Unread"] { 
	background-color: #1d74f5 !important;
}
```
But of course the aria-label is different in different languages, so this only works when Rocket.Chat is set to English. Reopening this issue so we can find a better solution.

**Comment by pbaity** [comment]
@ankar84 I think this rule fixes it:

**Comment by pbaity** [comment]
@ankar84 It looks like this also works:
```css
button.rcx-contextual-message__follow + div.rcx-box--full {
    background-color: #1d74f5 !important;
}
```
Since there's only one button element in all of Rocket.Chat that uses the `rcx-contextual-message__follow` class (as far as I can tell) and it only has one div sibling with the `rcx-box--full` class. I'm testing this out before opening a PR, if you also want to test and confirm it works without unexpected results.
