### ISSUE TITLE
Tables unreadable [w/ marked parser]

### ISSUE THREAD

**Issue by ulope** [pbaity/rocketchat-dark-mode#77]
**Describe the bug**
Inline tables (via markdown) are unreadable with light text on light background.

**To Reproduce**
1. Switch to dark mode
1. Switch markdown parser to `marked` (Admin -> Message -> Markdown)
1. Enable `Marked Tables` 
1. Post a table into a channel:
```
test | bla
--- | ---
something | foo
```
4. See that the table is unreadable

**Expected behavior**
The table to be readable

**Additional context**
This additional CSS fixes the issue for me (probably would need some touching up to fit with the rest of dark mode):
```css
body.dark-mode .message .body > table thead tr {
    background-color: #222;
}

body.dark-mode .message .body > table tr {
    background-color: #555;
}

body.dark-mode .message .body > table tr:nth-child(2n) {
    background-color: #444;
}
```

**Comment by pbaity** [comment]
@ulope Using our existing dark color variables I tried this:
```css
body.dark-mode .message .body > table thead tr {
    background-color: var(--color-darkest);
}

body.dark-mode .message .body > table tr {
    background-color: var(--color-dark);
}

body.dark-mode .message .body > table tr:nth-child(2n) {
    background-color: var(--color-darker);
}
```
This is the result:
![image](https://user-images.githubusercontent.com/39106297/96140930-7db50800-0ece-11eb-94c6-de046281a18c.png)
What do you think? Too dark? I may need to use hex colors instead of our variables if so.

**Comment by ulope** [comment]
Hm the alternating row pattern is a bit difficult to see, otherwise it's fine I'd say.

**Comment by pbaity** [comment]
Ah, I forgot I also have a `--color-dark-medium`. Changed the rules to this:
```css
body.dark-mode .message .body > table thead tr {
    background-color: var(--color-darkest);
}

body.dark-mode .message .body > table tr {
    background-color: var(--color-dark-medium);
}

body.dark-mode .message .body > table tr:nth-child(2n) {
    background-color: var(--color-dark);
}
```
Which results in:
![image](https://user-images.githubusercontent.com/39106297/96151072-05a00f80-0ed9-11eb-8b3e-22bef20ad5fb.png)
If you like this better, I'll open a PR for it.
